library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('libsystem', include('libsystem.urls')),
    path('', RedirectView.as_view(url='libsystem/', permanent=True)),
]

libsystem/urls.py
from django.urls import path
from . import views
from django.views import generic


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('loan_book/<int:pk>', views.loan_book, name='loan_book'),
    path('book/<uuid:pk>/return', views.return_book, name='return_book'),
    path('book/<int:pk>/rate/', views.book_rate, name='book_rate'),
    path('recommendation/', views.recommend_books, name='recommend'),

]

users/urls.py
from django.urls import path
from . import views
from .views import profile
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.custom_login, name='login'),
    path('logout', views.custom_logout, name='logout'),
    path('profile', views.profile, name='profile')


]

libsystem/models.py
from django.db import models
from django.urls import reverse
from users.models import CustomUser #django marks as error, though apparently works
from datetime import date
from django.db.models import Q
import uuid
# Create your models here.

class Genre(models.Model):
    ''' model rperesents book genres'''
    genre_name = models.CharField(max_length=200)
    #define an absolute url for genres

    def __str__(self):

        return self.genre_name

    def get_absolute_url(self):
        return reverse('genre_detail', args=[self.genre_name])

class Book(models.Model):
    ''' model representing the books,'''
    #no need for id column as django will create a column automatically
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    ratings = models.DecimalField(max_digits=3, decimal_places=1)
    genre = models.ManyToManyField(Genre)
    publisher = models.CharField(max_length=200)
    ratings_count = models.IntegerField()
    book_copies = models.IntegerField()



    def __str__(self):
        """returns."""
        return self.title

    def get_absolute_url(self):
        """returns url to get record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):

        return ', '.join(genre.genre_name for genre in self.genre.all()[:3])

    def related_books(self):
        # get all books with the same genre(s) as this book, excluding this book
        related_by_genre = Book.objects.filter(genre__in=self.genre.all()).exclude(id=self.id)
        # get all books with similar titles, excluding this book
        related_by_title = Book.objects.filter(
            Q(title__icontains=self.title) | Q(title__icontains=self.title.split()[0]),
            ~Q(id=self.id)
        )
        # combine the two sets of related books and order by rating (descending)
        related_books = related_by_genre.union(related_by_title).order_by('-ratings')[:5]
        return related_books

    display_genre.short_description = 'Genre'


class BookRental(models.Model):
    ''' representing a copy of a book that can be taken out on loan'''
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    due_date = models.DateField(null=True, blank=True) # use instead of dateRented, dateReturned as waste of space
    # book status moves to here as more apr
    loanee = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    book_status = (
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('u', 'Unavailable'),
    )
    status = models.CharField(
        max_length=1,
        choices=book_status,
        blank=True,
        default='u',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_date']
    @property
    def is_due(self):
        ''' determines if the book is overdue'''
        return bool(self.due_date and date.today() > self.due_date)

    def __str__(self):

        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    ''' model representing author'''
    fullname = models.CharField(max_length=80)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """returns url."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):

        return f'{self.fullname}'

class BookRating(models.Model):
    ''' model for book ratings,'''
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('book', 'user')

libsystem/forms.py
from django import forms
from .models import BookRating, Genre

class BookRatingForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=[(str(i), i) for i in range(1, 6)])

    class Meta:
        model = BookRating
        fields = ['rating']



class GenreForm(forms.ModelForm):
    genre_name = forms.ModelChoiceField(queryset=Genre.objects.all())
    class Meta:
        model = Genre
        fields = ['genre_name']

libsystem/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book, BookRental, Author, Genre, BookRating
from django.views import generic
from users.models import CustomUser
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, Http404
from .forms import BookRatingForm, GenreForm
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from django.urls import reverse


# Create your views here.
def index(request):
    ''' view function for home page of site.'''
    # counts books and rental status of books
    books_count = Book.objects.all().count()
    #rental_count = BookRental.objects.all().count()

    books_availability = BookRental.objects.filter(status__exact='a').count()

    authors_count = Author.objects.count()
    popular_books = Book.objects.order_by('-ratings_count', '-ratings')[:3]

    genres_count = Genre.objects.all().count()
    context = {
        'books_count': books_count,
        'authors_count': authors_count,
        'genres_count': genres_count,
        'popular_books': popular_books
    }

    return render(request, 'index.html', context=context)



class BookListView(generic.ListView):

    model = Book
    paginate_by = 8

class BookDetailView(generic.DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rating_form'] = BookRatingForm()
        context['related_books'] = self.object.related_books()
        return context

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 8
class AuthorDetailView(generic.DetailView):
    model = Author

class GenreListView(generic.ListView):
    model = Genre


@login_required
@require_POST # user must be logged in, method must be post
def loan_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    available_copy = book.bookrental_set.filter(status='a').first()

    if available_copy:
        available_copy.loanee = request.user
        available_copy.status = 'u'
        #set due date for 2 weeks after todays date
        available_copy.save()


    return redirect('book-detail', pk=book.pk)




@login_required
def return_book(request, pk):
    rental = get_object_or_404(BookRental, id=pk)
    if rental.loanee != request.user:
        messages.error(request, 'You are not the current loanee of this book.')
    else:
        rental.status = 'a'  # set book status as available
        rental.save()
        messages.success(request, f'Thank you for returning {rental.book.title}.')

    return redirect('book-detail', pk=rental.book.id)

@login_required # user must be logged in, method must be post
@require_POST
def book_rate(request, pk):
    book = get_object_or_404(Book, pk=pk)
    form = BookRatingForm(request.POST)
    if form.is_valid():
        rating = int(form.cleaned_data['rating'])
        BookRating.objects.create(book=book, user=request.user, rating=rating)
        book.ratings_count += 1
        book.ratings = (book.ratings * (book.ratings_count - 1) + rating) / book.ratings_count
        book.save()
        messages.success(request, 'Book rated successfully!')
    else:
        messages.error(request, 'Invalid rating')
    return redirect('book-detail', pk=book.pk)



def recommend_books(request):
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            selected_genre = form.cleaned_data['genre_name'].genre_name # cleans data
            genre_books = Book.objects.filter(genre__genre_name=selected_genre) # filters book by genre
            if len(genre_books) == 0:
                context = {'message': f"No books found for the genre {selected_genre}."}
            else:
                book_titles = [book.title for book in genre_books]
                count_vectorizer = CountVectorizer()
                count_matrix = count_vectorizer.fit_transform(book_titles) # transfrom titles into matrix
                cosine_sim = cosine_similarity(count_matrix, count_matrix) # calculates cosine between each pairs of books
                sim_scores = list(enumerate(cosine_sim[-1]))
                sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True) #sorts sim scores in desc order
                book_indices = [i[0] for i in sim_scores[1:6]] #selects top 5 similar books
                recommended_books = Book.objects.filter(title__in=[book_titles[i] for i in book_indices])
                context = {'recommended_books': recommended_books, 'form': GenreForm()}
    else:
        form = GenreForm()
        context = {'form': form}
    return render(request, 'libsystem/recommend.html', context=context)

libsystem/templates/libsystem/author_detail.html
{% extends "base.html" %}

{% block content %}
<body>
<h1>Author: {{ author }} </h1>

<h4>Books</h4>
<div style="margin-left:20px;margin-top:20px">
<dl>
{% for book in author.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookrental_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

</body>

libsystem/templates/libsystem/author_list.html
{% extends "base.html" %}

{% block content %}

<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }}
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}



{% endblock %}

libsystem/templates/libsystem/book_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Publisher:</strong> {{ book.publisher }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
<p><strong>Ratings:</strong> {{ book.ratings }}</p>

<div style="margin-left:20px;margin-top:20px" class="container mt-5">



     <!-- display related books -->
    {% if related_books %}
    <h4>Related Books</h4>
    <ul>
        {% for book in related_books %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
<!--fix bookrental, se -->
    {% for copy in book.bookrental_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'book_rate' book.pk %}">
    {% csrf_token %}
    {{ rating_form.as_p }}
    <button type="submit">Rate Book</button>
</form>
    {% if copy.loanee == user %}
    {% if copy.status != 'a' %}
    <form method="post" action="{% url 'return_book' copy.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Return Book</button>
    </form>
    {% endif %}
    {% endif %}
    {% endif %}
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_date }}</p>
    {% endif %}

    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>

    {% if user.is_authenticated and copy.status == 'a' %}
    <form method="post" action="{% url 'loan_book' book.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Loan Book</button>
    </form>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

libsystem/templates/libsystem/book_list.html
{% extends "base.html" %}

<div style="justify-content: center;">
{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}
</div>

libsystem/templates/libsystem/genre_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Genre List</h1>
  {% if genre_list %}
  <ul>
    {% for genre in genre_list %}
      <li>
        <a href="#">{{ genre.genre_name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}
<!-- Create a genre views, and list books by genre  -->

libsystem/templates/libsystem/recommend.html
{% extends "base.html" %}
<!-- List genres in scroll view-->
{% block content %}
  <h1>Recommendation</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }} <!-- renders form as para tags-->
    <button type="submit">Submit</button>
  </form>
  {% if recommended_books %}
    <h3>Recommended Books:</h3>
    <ul>
      {% for book in recommended_books %}
        <li>{{ book.title }} by {{ book.author }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if message %}
    <p>{{ message }}</p>
  {% endif %}
{% endblock %}