library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('libsystem', include('libsystem.urls')),
    path('', RedirectView.as_view(url='libsystem/', permanent=True)),
]

users/urls.py
from django.urls import path
from . import views
from .views import profile
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.custom_login, name='login'),
    path('logout', views.custom_logout, name='logout'),
    path('profile', views.profile, name='profile')


]

libsystem/models.py
from django.db import models
from django.urls import reverse
from users.models import CustomUser #django marks as error, though apparently works
from datetime import date
from django.db.models import Q
import uuid
# Create your models here.

class Genre(models.Model):
    ''' model rperesents book genres'''
    genre_name = models.CharField(max_length=200)
    #define an absolute url for genres

    def __str__(self):

        return self.genre_name

    def get_absolute_url(self):
        return reverse('genre_detail', args=[self.genre_name])

class Book(models.Model):
    ''' model representing the books,'''
    #no need for id column as django will create a column automatically
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    ratings = models.DecimalField(max_digits=3, decimal_places=1)
    genre = models.ManyToManyField(Genre)
    publisher = models.CharField(max_length=200)
    ratings_count = models.IntegerField()
    book_copies = models.IntegerField()



    def __str__(self):
        """returns."""
        return self.title

    def get_absolute_url(self):
        """returns url to get record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):

        return ', '.join(genre.genre_name for genre in self.genre.all()[:3])

    def related_books(self):
        # get all books with the same genre(s) as this book, excluding this book
        related_by_genre = Book.objects.filter(genre__in=self.genre.all()).exclude(id=self.id)
        # get all books with similar titles, excluding this book
        related_by_title = Book.objects.filter(
            Q(title__icontains=self.title) | Q(title__icontains=self.title.split()[0]),
            ~Q(id=self.id)
        )
        # combine the two sets of related books and order by rating (descending)
        related_books = related_by_genre.union(related_by_title).order_by('-ratings')[:5]
        return related_books

    display_genre.short_description = 'Genre'


class BookRental(models.Model):
    ''' representing a copy of a book that can be taken out on loan'''
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    due_date = models.DateField(null=True, blank=True) # use instead of dateRented, dateReturned as waste of space
    # book status moves to here as more apr
    loanee = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    book_status = (
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('u', 'Unavailable'),
    )
    status = models.CharField(
        max_length=1,
        choices=book_status,
        blank=True,
        default='u',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_date']
    @property
    def is_due(self):
        ''' determines if the book is overdue'''
        return bool(self.due_date and date.today() > self.due_date)

    def __str__(self):

        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    ''' model representing author'''
    fullname = models.CharField(max_length=80)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """returns url."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):

        return f'{self.fullname}'

class BookRating(models.Model):
    ''' model for book ratings,'''
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('book', 'user')

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    STATUS = (
        ('regular', 'regular'),
        ('administrator', 'adminstrator')
    )
    email = models.EmailField(unique=True, max_length=90)
    fullname = models.CharField(max_length=80)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    favourite_genres = models.CharField(max_length=150, blank=True)
    reading_history = models.CharField(max_length=300, blank=True)
    wishlist = models.CharField(max_length=300, blank=True)
    challenges = models.IntegerField(default=0)
    progress = models.IntegerField(default=0)
    status = models.CharField(max_length=60, choices=STATUS, default='regular') # d

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from .models import CustomUser



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text='Valid email address, please', required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class ChallengeProgressForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['challenges', 'progress']
        labels = {'challenges': 'Challenges',
                  'progress': 'Progress',}

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegistrationForm, ChallengeProgressForm
from .decorators import user_not_authenticated



@user_not_authenticated
def register(request):

    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            for error in list(form.errors.values()):
                print(request, error)

    else:
        form = UserRegistrationForm()

        print(form.errors)

    return render(
        request=request,
        template_name='register.html',
        context={'form': form}
    )


@login_required
def custom_logout(request):
    logout(request)
    # messages.info(request, "You've successfully logged out!")
    return redirect("index")

@user_not_authenticated #does job of authenticating user
def custom_login(request):


    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user is not None:
                login(request, user)
                messages.success(request, "Hello! You have been logged in")
                return redirect('index')

        else:
            for error in list(form.errors.values()):
                messages.add_message(request, messages.ERROR, error)

    form = AuthenticationForm()

    return render(
        request=request,
        template_name="users/login.html",
        context={'form': form}
    )

@login_required
def profile(request):
    user = request.user
    if request.method == 'POST':
        challenge_progress = ChallengeProgressForm(request.POST, instance=user)

        if challenge_progress.is_valid():
            challenge_progress.save()
            return redirect('users/profile.html')

    else:
        challenge_progress = ChallengeProgressForm(instance=user)

    context = {'user': user,
               'challenge_progress': challenge_progress}

    return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                    {{ form}}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small><br>

        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}

<h1>{{ user.fullname }} Profile</h1>
<p>Email: {{ user.email }}</p>
<p>First Name: {{ user.first_name }}</p>
<p>Last Name: {{ user.last_name }}</p>


<h2>Challenges</h2>
<p>Number of books to read: {{ user.challenges }}</p>
<form method="post" action="{% url 'profile' %}">
    {% csrf_token %}
    <label for="challenges">Set a challenge: </label>
    <input type="number" id="challenges" name="challenges" min="0" value="{{ user.challenges }}">
    <button type="submit">Update</button>
</form>
<h2>Progress</h2>
<p>Number of books finished: {{ user.progress }}</p>
<form method="post" action="{% url 'profile' %}">
    {% csrf_token %}
    <label for="progress">Update progress: </label>
    <input type="number" id="progress" name="progress" min="0" value="{{ user.progress }}">
    <button type="submit">Update</button>
</form>
{% if user.challenges == user.progress %}
<p>Congratulations! You have completed your challenges.</p>
{% endif %}

<h2>Borrowed books: </h2>
<ul>
    {% for book_rental in user.bookrental_set.all %}
    <li>{{ book_rental.book.title }} - {{ book_rental.status }}</li>
    {% empty %}
    <li>No Books rented yet.</li>
    {% endfor %}
</ul>


{% endblock %}